version: '3'
services:
  reverse-proxy:
    image: reverse-proxy
    build:
      context: reverse-proxy
      dockerfile: Dockerfile
    networks:
      - swm-net
    ports:
      - 80:80

  service-1:
    image: service-1
    build:
      context: service-1
      dockerfile: Dockerfile
    networks:
      - swm-net

  service-2:
    image: service-2
    build:
      context: service-2
      dockerfile: Dockerfile
    networks:
      - swm-net

networks:
  swm-net:
    external: true
